# Step I - Import Libraries and get the list of all equity derivatives

In [1]:
import numpy as np
import pandas as pd
import datetime as dt
import pandas_datareader.data as pdr
from nsepy import get_history
import talib as ta

C:\Users\akshay\anaconda3\lib\site-packages\pandas_datareader\compat\__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal

In [2]:
stocks = pd.read_csv('NSE_derivatives_stocks.csv',encoding= 'unicode_escape')

In [3]:
ticker = stocks['ticker']

In [4]:
ticker = [item+'.NS' for item in ticker]

In [5]:
ticker

['ACC.NS',
 'ADANIENT.NS',
 'ADANIPORTS.NS',
 'ADANIPOWER.NS',
 'AMARAJABAT.NS',
 'AMBUJACEM.NS',
 'APOLLOHOSP.NS',
 'APOLLOTYRE.NS',
 'ASHOKLEY.NS',
 'ASIANPAINT.NS',
 'AUROPHARMA.NS',
 'AXISBANK.NS',
 'BAJAJ-AUTO.NS',
 'BAJFINANCE.NS',
 'BAJAJFINSV.NS',
 'BALKRISIND.NS',
 'BANDHANBNK.NS',
 'BANKBARODA.NS',
 'BATAINDIA.NS',
 'BERGEPAINT.NS',
 'BEL.NS',
 'BHARATFORG.NS',
 'BPCL.NS',
 'BHARTIARTL.NS',
 'INFRATEL.NS',
 'BHEL.NS',
 'BIOCON.NS',
 'BOSCHLTD.NS',
 'BRITANNIA.NS',
 'CADILAHC.NS',
 'CANBK.NS',
 'CENTURYTEX.NS',
 'CESC.NS',
 'CHOLAFIN.NS',
 'CIPLA.NS',
 'COALINDIA.NS',
 'COLPAL.NS',
 'CONCOR.NS',
 'CUMMINSIND.NS',
 'DABUR.NS',
 'DIVISLAB.NS',
 'DLF.NS',
 'DRREDDY.NS',
 'EICHERMOT.NS',
 'EQUITAS.NS',
 'ESCORTS.NS',
 'EXIDEIND.NS',
 'FEDERALBNK.NS',
 'GAIL.NS',
 'GLENMARK.NS',
 'GMRINFRA.NS',
 'GODREJCP.NS',
 'GODREJPROP.NS',
 'GRASIM.NS',
 'HAVELLS.NS',
 'HCLTECH.NS',
 'HDFCBANK.NS',
 'HDFC.NS',
 'HDFCLIFE.NS',
 'HEROMOTOCO.NS',
 'HINDALCO.NS',
 'HINDPETRO.NS',
 'HINDUNILVR.NS',
 'ICICIBANK.NS',
 'ICICIPRULI.NS',
 'NAUKRI.NS',
 'IDEA.NS',
 'IDFCFIRSTB.NS',
 'IBULHSGFIN.NS',
 'IOC.NS',
 'IGL.NS',
 'INDUSINDBK.NS',
 'INFY.NS',
 'INDIGO.NS',
 'ITC.NS',
 'JINDALSTEL.NS',
 'JSWSTEEL.NS',
 'JUBLFOOD.NS',
 'JUSTDIAL.NS',
 'KOTAKBANK.NS',
 'L&TFH.NS',
 'LT.NS',
 'LICHSGFIN.NS',
 'LUPIN.NS',
 'M&MFIN.NS',
 'MGL.NS',
 'M&M.NS',
 'MANAPPURAM.NS',
 'MARICO.NS',
 'MARUTI.NS',
 'MFSL.NS',
 'MINDTREE.NS',
 'MOTHERSUMI.NS',
 'MRF.NS',
 'MUTHOOTFIN.NS',
 'NATIONALUM.NS',
 'NCC.NS',
 'NESTLEIND.NS',
 'NIITTECH.NS',
 'NMDC.NS',
 'NTPC.NS',
 'ONGC.NS',
 'OIL.NS',
 'PAGEIND.NS',
 'PETRONET.NS',
 'PIDILITIND.NS',
 'PEL.NS',
 'PFC.NS',
 'POWERGRID.NS',
 'PNB.NS',
 'PVR.NS',
 'RBLBANK.NS',
 'RELIANCE.NS',
 'RECLTD.NS',
 'SHREECEM.NS',
 'SRTRANSFIN.NS',
 'SIEMENS.NS',
 'SRF.NS',
 'SBIN.NS',
 'SAIL.NS',
 'SUNPHARMA.NS',
 'SUNTV.NS',
 'TATACHEM.NS',
 'TCS.NS',
 'TATACONSUM.NS',
 'TATAMOTORS.NS',
 'TATAPOWER.NS',
 'TATASTEEL.NS',
 'TECHM.NS',
 'RAMCOCEM.NS',
 'TITAN.NS',
 'TORNTPHARM.NS',
 'TORNTPOWER.NS',
 'TVSMOTOR.NS',
 'UJJIVAN.NS',
 'ULTRACEMCO.NS',
 'UBL.NS',
 'MCDOWELL-N.NS',
 'UPL.NS',
 'VEDL.NS',
 'VOLTAS.NS',
 'WIPRO.NS',
 'YESBANK.NS',
 'ZEEL.NS']

# Step II - Fetch data from Yahoo Finance API

In [6]:
start = dt.datetime.today() - dt.timedelta(360)
end = dt.datetime.today()

In [7]:
data = pdr.get_data_yahoo(ticker,start,end)

In [8]:
data_close = data['Adj Close']
price = data_close.copy()

In [9]:
price

Symbols,ACC.NS,ADANIENT.NS,ADANIPORTS.NS,ADANIPOWER.NS,AMARAJABAT.NS,AMBUJACEM.NS,APOLLOHOSP.NS,APOLLOTYRE.NS,ASHOKLEY.NS,ASIANPAINT.NS,...,UJJIVAN.NS,ULTRACEMCO.NS,UBL.NS,MCDOWELL-N.NS,UPL.NS,VEDL.NS,VOLTAS.NS,WIPRO.NS,YESBANK.NS,ZEEL.NS
Date,,,,,,,,,,,,,,,,,,,,,
2019-05-08,1570.111328,119.657883,365.565430,41.349998,619.539856,211.307083,1163.502563,180.631958,78.562172,1370.213257,...,306.543488,4496.126953,1359.031860,526.799988,636.093628,154.191284,568.907654,289.680511,156.452667,328.290619
2019-05-09,1573.215698,118.866104,359.733002,40.950001,619.101501,211.901321,1162.806519,174.555939,77.556717,1339.065308,...,308.290619,4466.952148,1369.512817,525.799988,627.659973,152.014801,566.391846,289.879700,165.747345,354.328156
2019-05-10,1579.128784,118.767128,368.283966,41.450001,618.468384,212.693665,1179.658203,179.878342,78.516472,1326.062378,...,312.383850,4422.915039,1349.000000,537.900024,634.340454,150.854019,572.262024,289.182526,159.469788,367.495422
2019-05-13,1560.059204,116.391785,360.573273,38.450001,609.652527,207.989151,1165.490845,175.403732,75.865738,1317.607910,...,307.442017,4327.359863,1351.345825,527.900024,630.470886,149.161209,564.517456,287.937561,150.564392,338.636322
2019-05-14,1549.514282,122.082710,366.306854,40.799999,616.081726,211.059464,1135.864014,169.233521,77.328209,1305.494751,...,306.194092,4412.990234,1365.869385,531.099976,631.760681,155.497177,564.320068,283.455658,151.683655,342.843903
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-24,1156.599976,134.649994,270.649994,30.650000,532.099976,167.949997,1359.500000,89.949997,44.950001,1827.550049,...,164.100006,3307.949951,880.750000,519.500000,335.850006,77.949997,487.149994,177.750000,26.600000,145.149994
2020-04-27,1137.900024,134.600006,271.149994,30.850000,541.650024,172.300003,1418.900024,89.699997,44.299999,1851.349976,...,164.949997,3360.649902,908.299988,522.049988,349.350006,78.449997,490.799988,182.050003,27.049999,149.750000
2020-04-28,1126.500000,139.300003,272.950012,30.150000,545.549988,167.699997,1426.449951,89.500000,44.549999,1824.400024,...,175.449997,3394.000000,931.000000,522.900024,360.500000,76.849998,496.799988,179.699997,27.250000,152.449997
2020-04-29,1122.199951,139.500000,287.649994,31.250000,540.200012,169.500000,1417.949951,95.650002,47.950001,1767.500000,...,175.899994,3434.350098,943.849976,532.299988,360.600006,79.150002,491.399994,180.649994,28.049999,159.399994
2020-04-30,1179.099976,141.399994,290.100006,31.650000,570.849976,171.649994,1394.349976,96.300003,52.349998,1758.699951,...,175.800003,3534.300049,938.599976,536.650024,420.049988,89.550003,505.399994,190.949997,27.900000,159.350006

In [10]:
price_pct = price.pct_change(1)
price_pct

Symbols,ACC.NS,ADANIENT.NS,ADANIPORTS.NS,ADANIPOWER.NS,AMARAJABAT.NS,AMBUJACEM.NS,APOLLOHOSP.NS,APOLLOTYRE.NS,ASHOKLEY.NS,ASIANPAINT.NS,...,UJJIVAN.NS,ULTRACEMCO.NS,UBL.NS,MCDOWELL-N.NS,UPL.NS,VEDL.NS,VOLTAS.NS,WIPRO.NS,YESBANK.NS,ZEEL.NS
Date,,,,,,,,,,,,,,,,,,,,,
2019-05-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-05-09,0.001977,-0.006617,-0.015955,-0.009673,-0.000708,0.002812,-0.000598,-0.033638,-0.012798,-0.022732,...,0.005699,-0.006489,0.007712,-0.001898,-0.013259,-0.014115,-0.004422,0.000688,0.059409,0.079312
2019-05-10,0.003759,-0.000833,0.023770,0.012210,-0.001023,0.003739,0.014492,0.030491,0.012375,-0.009710,...,0.013277,-0.009858,-0.014978,0.023013,0.010643,-0.007636,0.010364,-0.002405,-0.037874,0.037161
2019-05-13,-0.012076,-0.020000,-0.020937,-0.072376,-0.014254,-0.022119,-0.012010,-0.024876,-0.033760,-0.006376,...,-0.015820,-0.021605,0.001739,-0.018591,-0.006100,-0.011222,-0.013533,-0.004305,-0.055844,-0.078529
2019-05-14,-0.006759,0.048895,0.015901,0.061118,0.010546,0.014762,-0.025420,-0.035177,0.019277,-0.009193,...,-0.004059,0.019788,0.010747,0.006062,0.002046,0.042477,-0.000350,-0.015566,0.007434,0.012425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-24,-0.028435,-0.041637,-0.025036,-0.055470,-0.046159,-0.020414,-0.017738,-0.035389,-0.037473,0.003239,...,-0.086048,-0.039001,-0.042663,-0.018978,-0.037403,0.004510,-0.041421,-0.017413,-0.060071,-0.078705
2020-04-27,-0.016168,-0.000371,0.001847,0.006525,0.017948,0.025901,0.043693,-0.002779,-0.014461,0.013023,...,0.005180,0.015931,0.031280,0.004909,0.040197,0.006414,0.007493,0.024191,0.016917,0.031691
2020-04-28,-0.010018,0.034918,0.006638,-0.022690,0.007200,-0.026698,0.005321,-0.002230,0.005643,-0.014557,...,0.063656,0.009924,0.024992,0.001628,0.031916,-0.020395,0.012225,-0.012909,0.007394,0.018030
2020-04-29,-0.003817,0.001436,0.053856,0.036484,-0.009807,0.010733,-0.005959,0.068715,0.076319,-0.031188,...,0.002565,0.011889,0.013802,0.017977,0.000277,0.029928,-0.010870,0.005287,0.029358,0.045589
2020-04-30,0.050704,0.013620,0.008517,0.012800,0.056738,0.012684,-0.016644,0.006796,0.091762,-0.004979,...,-0.000568,0.029103,-0.005562,0.008172,0.164864,0.131396,0.028490,0.057016,-0.005348,-0.000314

# Step III - Apply the scans

# 1. Price Change > 3%

In [11]:
scanned_stocks = []

In [12]:
for i in ticker:
    if price_pct[i][-1] > 0.03:
        scanned_stocks.append(i)

In [13]:
price[scanned_stocks]

Symbols,ACC.NS,AMARAJABAT.NS,ASHOKLEY.NS,BAJAJ-AUTO.NS,BANDHANBNK.NS,BHARATFORG.NS,BHARTIARTL.NS,INFRATEL.NS,BHEL.NS,BOSCHLTD.NS,...,SAIL.NS,TCS.NS,TATAMOTORS.NS,TATASTEEL.NS,TECHM.NS,TITAN.NS,TVSMOTOR.NS,UPL.NS,VEDL.NS,WIPRO.NS
Date,,,,,,,,,,,,,,,,,,,,,
2019-05-08,1570.111328,619.539856,78.562172,2768.659424,568.097107,456.118652,324.500000,259.891663,58.915295,17194.320312,...,52.020329,2105.189453,185.100006,509.335419,774.743713,1078.757324,489.173676,636.093628,154.191284,289.680511
2019-05-09,1573.215698,619.101501,77.556717,2792.201416,568.743530,454.293793,315.450012,260.281433,59.583160,17027.625000,...,51.331318,2124.453125,186.350006,505.924561,781.841370,1094.363525,482.082733,627.659973,152.014801,289.879700
2019-05-10,1579.128784,618.468384,78.516472,2776.569336,571.528076,450.200165,324.100006,255.555237,60.251026,17110.476562,...,51.675823,2088.516602,185.899994,474.398651,780.634277,1121.761108,471.223236,634.340454,150.854019,289.182526
2019-05-13,1560.059204,609.652527,75.865738,2782.700684,550.196472,444.626923,318.649994,258.673553,57.102512,17066.716797,...,49.953297,2081.622559,180.750000,460.268036,789.228577,1134.245972,461.405060,630.470886,149.161209,287.937561
2019-05-14,1549.514282,616.081726,77.328209,2749.423340,539.804138,450.249481,336.600006,263.156097,61.014301,16661.289062,...,47.000393,2046.028564,184.500000,457.588104,762.914490,1144.204224,459.024902,631.760681,155.497177,283.455658
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-24,1156.599976,532.099976,44.950001,2445.350098,198.449997,263.250000,494.250000,152.000000,20.650000,10212.500000,...,26.900000,1818.550049,74.199997,267.549988,503.450012,906.049988,297.000000,335.850006,77.949997,177.750000
2020-04-27,1137.900024,541.650024,44.299999,2505.750000,208.350006,271.200012,494.049988,157.399994,20.650000,10114.700195,...,26.549999,1836.599976,75.250000,271.649994,511.700012,927.750000,299.299988,349.350006,78.449997,182.050003
2020-04-28,1126.500000,545.549988,44.549999,2463.699951,221.100006,266.750000,485.649994,159.399994,20.950001,9982.099609,...,27.400000,1859.050049,76.949997,273.549988,520.400024,932.849976,296.299988,360.500000,76.849998,179.699997
2020-04-29,1122.199951,540.200012,47.950001,2499.149902,234.449997,282.049988,496.000000,163.000000,20.950001,10024.000000,...,30.200001,1905.650024,78.150002,282.649994,528.700012,925.400024,307.899994,360.600006,79.150002,180.649994
2020-04-30,1179.099976,570.849976,52.349998,2623.300049,262.350006,309.200012,514.299988,174.399994,22.450001,10612.500000,...,31.850000,2014.449951,93.250000,298.299988,546.250000,970.049988,328.350006,420.049988,89.550003,190.949997

# 2. Price > 200 SMA and RSI(2) > 50

In [14]:
final_stocks = []

In [15]:
for i in scanned_stocks:
    if (ta.SMA(price[i],200)[-1] < price[i][-1]) & (ta.RSI(price[i],2)[-1] > 50):
        final_stocks.append(i)

In [16]:
price[final_stocks]

Symbols,BHARTIARTL.NS,HCLTECH.NS,NAUKRI.NS,JUBLFOOD.NS,MINDTREE.NS,MUTHOOTFIN.NS
Date,,,,,,
2019-05-08,324.500000,561.320251,1944.753662,1252.946045,929.613770,547.954712
2019-05-09,315.450012,563.302673,1901.379639,1259.248413,929.566345,552.834534
2019-05-10,324.100006,538.547363,1934.993164,1254.980713,924.731018,559.324646
2019-05-13,318.649994,537.060608,1912.783447,1233.245605,928.286377,534.096008
2019-05-14,336.600006,529.229980,1890.573486,1192.901611,924.588806,556.543152
...,...,...,...,...,...,...
2020-04-24,494.250000,468.100006,2327.100098,1478.699951,780.349976,813.950012
2020-04-27,494.049988,483.100006,2322.750000,1484.800049,879.650024,820.049988
2020-04-28,485.649994,471.100006,2392.250000,1521.550049,867.299988,826.599976
2020-04-29,496.000000,491.750000,2434.750000,1553.550049,881.599976,824.200012
2020-04-30,514.299988,543.549988,2547.600098,1608.500000,915.950012,862.700012

In [17]:
cp_stocks = price[final_stocks].iloc[-1].round(1)
cp_stocks

Symbols
BHARTIARTL.NS     514.3
HCLTECH.NS        543.5
NAUKRI.NS        2547.6
JUBLFOOD.NS      1608.5
MINDTREE.NS       916.0
MUTHOOTFIN.NS     862.7
Name: 2020-04-30 00:00:00, dtype: float64

# Step IV - Find the Entry, Stop loss and Target price

In [18]:
entry_price = (cp_stocks*1.01).round(1)
entry_price = pd.DataFrame(entry_price)
sl_price = (entry_price* 1.03).round(1)
tgt_price = (entry_price* 0.94).round(1)

In [19]:
order_df = pd.concat([entry_price,sl_price,tgt_price],axis =1,ignore_index = True)

In [20]:
order_df.rename(columns = {0:'Entry Price', 1:'Stop Loss', 2:'Target'},inplace = True)

In [21]:
order_df

               Entry Price  Stop Loss  Target
Symbols
BHARTIARTL.NS        519.4      535.0   488.2
HCLTECH.NS           548.9      565.4   516.0
NAUKRI.NS           2573.1     2650.3  2418.7
JUBLFOOD.NS         1624.6     1673.3  1527.1
MINDTREE.NS          925.2      953.0   869.7
MUTHOOTFIN.NS        871.3      897.4   819.0